//
// Created by oleg on 22.04.24.
//

#ifndef STREAMINGGATEWAYCROW_TEST_SHARED_MEMORY_MANAGER_H
#define STREAMINGGATEWAYCROW_TEST_SHARED_MEMORY_MANAGER_H

#endif //STREAMINGGATEWAYCROW_TEST_SHARED_MEMORY_MANAGER_H
